# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8839a0b91b1348f9314282cd4faa14f891714838180963e0491677cf0e18bdebc9972ad578a10eb2323c75822c22b2c11a97e110a5f0f598e941c6f6dfc39759

test:
  secret_key_base: 77730ba04f9bc98b86a525a2d84d924e3de2048ae68d1a419f4671987c7678fee35495dc2250437cdb16ba33a43a845c88fb76e53a241c206475ccb1e0ce24b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
